### PR TITLE
Arrow key support for navigating results

### PR DESCRIPTION
**Pull request by iangilman**

### CODE REVIEW

**Comment by case** [comment]
@iangilman I might be (probably am!) doing something wrong here, but the keyboard shortcuts aren't working locally for some reason. Here's what I'm trying:

1. nuke the `dist/` dir, to make sure an old version isn't the problem
1. make sure I have a Mashape key (or clientId) in my `config.js` file
1. `gulp` to pull up the demo page in my browser
1. search for `acme coffee` to see the search and results working √
1. try the Up or Down arrow keys to select a result — not working

**Comment by iangilman** [comment]
D'oh! That's what I get for not testing in Chrome. Here is the fix: 

https://github.com/domainr/domainr-search-box/pull/10

Speaking of not testing, I actually don't have a way to test IE...do you?

**Comment by case** [comment]
http://modern.ie !

**Comment by iangilman** [comment]
Fair enough :)

**Comment by iangilman** [comment]
@case I'm pleased to report that I finally got the virtual machine at modern.ie working and have verified that the keys work there too :)

**Comment by case** [comment]
Hooray! Thanks for checking.

**Pull request merged**
